<a href="https://colab.research.google.com/github/shimaa83/Arabic_text_classification/blob/main/arabic_classification_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [5]:
pip install camel-tools

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 KB 5.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 44.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.9/240.9 KB 27.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 418.2/418.2 KB 36.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 79.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 24.1 MB/s eta 0:00:00
  Created wheel for camel-kenlm: filename=camel_kenlm-2021.12.27-cp38-cp38-linux_x86_64.whl size=2970619 sha256=4d9a6d87f6dd753fff4af37349acf15a1a723c9e9bdf3295b6c0e5b73911e903
  Stored in directory: /root/.cache/pip/wheels/2c/7b/f0/837fcdb48cd99564b1163d90392f350cb933fce3bf122eadcd
  Created wh

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/nlp/ar_reviews_3.tsv', sep='\t')
df.head()

label                                               text
0  Positive  ممتاز نوعا ما . النظافة والموقع والتجهيز والشا...
1  Positive  أحد أسباب نجاح الإمارات أن كل شخص في هذه الدول...
2  Positive  هادفة .. وقوية. تنقلك من صخب شوارع القاهرة الى...
3  Positive  خلصنا .. مبدئيا اللي مستني ابهار زي الفيل الاز...
4  Positive  ياسات جلوريا جزء لا يتجزأ من دبي . فندق متكامل...

In [ ]:
#removes diacritization from all words

In [ ]:
from camel_tools.utils.dediac import dediac_ar
df['text'] = df['text'].apply(dediac_ar)

In [ ]:
def removePunctuation (texts):
    import re
    ## replace arabic specific punctuation
    texts = re.sub(r'\u060c|\u061b|\u061f|\u066c|\u066d|\u06d4|\u06dd|\u06de|\u06e9',' ',texts)
    ## replace other junk characters that sometimes show up
    texts = re.sub(r'[\u200C-\u200F]|&nbsp|~|\u2018|\u2022|\u2013|\u2026|\u201c|\u201d|\u2019|\ufd3e|\ufd3f',' ',texts)
    texts = re.sub(r'\xbb|\xab|\xf7|\xb7',' ', texts)
    ## remove general punctuation
    texts = re.sub(r',|/|`|\$|\.|\^|\*|\+|\?|\{|\|\}|\!|\\|\[|\]|\:|\||\}|\<|\>|\#|\%|\(|\)|\@|\&|\-|_|\=|\[|\\\\|\;|\'|\"',' ',texts)
    #remove url
    texts = re.sub(r'^https?:\/\/.*[\r\n]*', '<URL>', texts)

    return texts 

In [ ]:
df['text'] = df['text'].apply(removePunctuation)

In [ ]:
!pip install arabic-stopwords


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 360.5/360.5 KB 12.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.4/126.4 KB 15.4 MB/s eta 0:00:00


In [ ]:
import arabicstopwords.arabicstopwords as ast
stop_words = ast.stopwords_list()
# a small function to remove stop words
def remove_stop_words(text):
    return ' '.join(word for word in text.split() if word not in stop_words)

In [ ]:
df['text'] = df['text'].apply(remove_stop_words)

In [ ]:
## encoding our categorical labels
df['label'] = df['label'].astype('category').cat.codes

In [ ]:
df.head()

label                                               text
0      2  ممتاز نوعا النظافة والموقع والتجهيز والشاطيء ا...
1      2  أحد أسباب نجاح الإمارات شخص الدولة يعشق ترابها...
2      2  هادفة وقوية تنقلك صخب شوارع القاهرة الى هدوء ج...
3      2  خلصنا مبدئيا اللي مستني ابهار زي الفيل الازرق ...
4      2  ياسات جلوريا جزء يتجزأ دبي فندق متكامل الخدمات...

In [ ]:
df.to_csv('/content/drive/MyDrive/nlp/cleaning.tsv', sep="\t")


In [4]:
df = pd.read_csv('/content/drive/MyDrive/nlp/cleaning.tsv', sep='\t')
df.head()

Unnamed: 0  label                                               text
0           0      2  ممتاز نوعا النظافة والموقع والتجهيز والشاطيء ا...
1           1      2  أحد أسباب نجاح الإمارات شخص الدولة يعشق ترابها...
2           2      2  هادفة وقوية تنقلك صخب شوارع القاهرة الى هدوء ج...
3           3      2  خلصنا مبدئيا اللي مستني ابهار زي الفيل الازرق ...
4           4      2  ياسات جلوريا جزء يتجزأ دبي فندق متكامل الخدمات...

In [8]:
import camel_tools.utils.normalize 
df['text'] = df['text'].apply(str).apply(camel_tools.utils.normalize.normalize_alef_ar)

In [9]:
df['text'] = df['text'].apply(str).apply(camel_tools.utils.normalize.normalize_teh_marbuta_ar)

In [11]:
pip install tensorflow


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [12]:
X = df['text']
y = df['label']

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

print('Training Data Shape:', X_train.shape)
print('Testing Data Shape: ', X_test.shape)

Training Data Shape: (47999,)
Testing Data Shape:  (12000,)


In [22]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(X_train)
X_train_counts.shape


(47999, 183797)

In [23]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape


(47999, 183797)

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

text_clf = Pipeline([('vect', CountVectorizer()),('tfidf', TfidfTransformer()),('clf', LogisticRegression()),])
text_clf.fit(X_train, y_train)  
predictions = text_clf.predict(X_test)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [26]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))
print(metrics.classification_report(y_test,predictions)) 

[[2197  848  939]
 [ 772 2900  371]
 [ 769  349 2855]]
              precision    recall  f1-score   support

           0       0.59      0.55      0.57      3984
           1       0.71      0.72      0.71      4043
           2       0.69      0.72      0.70      3973

    accuracy                           0.66     12000
   macro avg       0.66      0.66      0.66     12000
weighted avg       0.66      0.66      0.66     12000



In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB

text_clf = Pipeline([('vect', CountVectorizer()),('tfidf', TfidfTransformer()),('clf', MultinomialNB()),])

In [ ]:
text_clf.fit(X_train, y_train)  
predictions = text_clf.predict(X_test)

In [ ]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))
print(metrics.classification_report(y_test,predictions)) 

[[2282  971  731]
 [ 884 2855  304]
 [ 959  463 2551]]
              precision    recall  f1-score   support

           0       0.55      0.57      0.56      3984
           1       0.67      0.71      0.69      4043
           2       0.71      0.64      0.67      3973

    accuracy                           0.64     12000
   macro avg       0.64      0.64      0.64     12000
weighted avg       0.64      0.64      0.64     12000



In [ ]:
from sklearn.linear_model import SGDClassifier
text_clf_svm = Pipeline([('vect', CountVectorizer()),('tfidf', TfidfTransformer()),('clf-svm', SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3,random_state=42)),])

In [ ]:
text_clf_svm.fit(X_train, y_train)  
predictions = text_clf_svm.predict(X_test)

In [ ]:
print(metrics.confusion_matrix(y_test,predictions))
print(metrics.classification_report(y_test,predictions)) 

[[1284 1263 1437]
 [ 249 3234  560]
 [ 236  551 3186]]
              precision    recall  f1-score   support

           0       0.73      0.32      0.45      3984
           1       0.64      0.80      0.71      4043
           2       0.61      0.80      0.70      3973

    accuracy                           0.64     12000
   macro avg       0.66      0.64      0.62     12000
weighted avg       0.66      0.64      0.62     12000

