In [ ]:
D:\NLP\arabic data set\archive\ar_reviews_3.tsv

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('D:/NLP/arabic data set/archive/ar_reviews_2.tsv', sep='\t')
df.head()

label                                               text
0  Positive  ممتاز نوعا ما . النظافة والموقع والتجهيز والشا...
1  Positive  أحد أسباب نجاح الإمارات أن كل شخص في هذه الدول...
2  Positive  هادفة .. وقوية. تنقلك من صخب شوارع القاهرة الى...
3  Positive  خلصنا .. مبدئيا اللي مستني ابهار زي الفيل الاز...
4  Positive  ياسات جلوريا جزء لا يتجزأ من دبي . فندق متكامل...

In [3]:
df.shape

(87948, 2)

In [4]:
df.isnull().sum()

label    0
text     0
dtype: int64

In [5]:
df['label'].value_counts()

Mixed       30000
Negative    29990
Positive    27958
Name: label, dtype: int64

In [6]:
X = df['text']
y = df['label']

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

print('Training Data Shape:', X_train.shape)
print('Testing Data Shape: ', X_test.shape)

Training Data Shape: (58925,)
Testing Data Shape:  (29023,)


In [8]:
y_train.value_counts()

Negative    20121
Mixed       19951
Positive    18853
Name: label, dtype: int64

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

X_train_tfidf = vectorizer.fit_transform(X_train) # remember to use the original X_train set
X_train_tfidf.shape

(58925, 232458)

In [12]:
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC

text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LinearSVC()),])


text_clf.fit(X_train, y_train)  


predictions = text_clf.predict(X_test)

In [13]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[5455 2208 2386]
 [1911 7045  913]
 [1842  917 6346]]


In [14]:
print(metrics.classification_report(y_test,predictions)) 

              precision    recall  f1-score   support

       Mixed       0.59      0.54      0.57     10049
    Negative       0.69      0.71      0.70      9869
    Positive       0.66      0.70      0.68      9105

    accuracy                           0.65     29023
   macro avg       0.65      0.65      0.65     29023
weighted avg       0.65      0.65      0.65     29023



In [15]:
from sklearn.naive_bayes import BernoulliNB
text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf' ,BernoulliNB()),])


text_clf.fit(X_train, y_train)  


predictions = text_clf.predict(X_test)


In [16]:
print(metrics.confusion_matrix(y_test,predictions))

[[4842 3220 1987]
 [1511 7667  691]
 [1845 1536 5724]]


In [17]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

       Mixed       0.59      0.48      0.53     10049
    Negative       0.62      0.78      0.69      9869
    Positive       0.68      0.63      0.65      9105

    accuracy                           0.63     29023
   macro avg       0.63      0.63      0.62     29023
weighted avg       0.63      0.63      0.62     29023



In [19]:
from sklearn.tree import DecisionTreeClassifier
text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf' ,DecisionTreeClassifier()),])


text_clf.fit(X_train, y_train)  


predictions = text_clf.predict(X_test)

In [20]:
print(metrics.confusion_matrix(y_test,predictions))

[[4849 2650 2550]
 [2389 5742 1738]
 [2261 1639 5205]]


In [21]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

       Mixed       0.51      0.48      0.50     10049
    Negative       0.57      0.58      0.58      9869
    Positive       0.55      0.57      0.56      9105

    accuracy                           0.54     29023
   macro avg       0.54      0.55      0.54     29023
weighted avg       0.54      0.54      0.54     29023



In [22]:
from sklearn.ensemble import RandomForestClassifier, VotingClassifier


In [23]:
text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf' ,RandomForestClassifier()),])


text_clf.fit(X_train, y_train)  


predictions = text_clf.predict(X_test)

In [24]:
print(metrics.confusion_matrix(y_test,predictions))

[[5303 2696 2050]
 [1708 7283  878]
 [1858 1294 5953]]


In [25]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

       Mixed       0.60      0.53      0.56     10049
    Negative       0.65      0.74      0.69      9869
    Positive       0.67      0.65      0.66      9105

    accuracy                           0.64     29023
   macro avg       0.64      0.64      0.64     29023
weighted avg       0.64      0.64      0.64     29023



In [26]:
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf' ,AdaBoostClassifier()),])


text_clf.fit(X_train, y_train)  


predictions = text_clf.predict(X_test)

In [27]:
print(metrics.confusion_matrix(y_test,predictions))

[[5566 2476 2007]
 [2552 6379  938]
 [2739 1329 5037]]


In [28]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

       Mixed       0.51      0.55      0.53     10049
    Negative       0.63      0.65      0.64      9869
    Positive       0.63      0.55      0.59      9105

    accuracy                           0.59     29023
   macro avg       0.59      0.58      0.59     29023
weighted avg       0.59      0.59      0.59     29023



In [29]:
from sklearn.linear_model import LogisticRegression
text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf' ,LogisticRegression()),])


text_clf.fit(X_train, y_train)  


predictions = text_clf.predict(X_test)

C:\Users\ma\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [30]:
print(metrics.confusion_matrix(y_test,predictions))

[[5771 2061 2217]
 [1842 7220  807]
 [1857  800 6448]]


In [31]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

       Mixed       0.61      0.57      0.59     10049
    Negative       0.72      0.73      0.72      9869
    Positive       0.68      0.71      0.69      9105

    accuracy                           0.67     29023
   macro avg       0.67      0.67      0.67     29023
weighted avg       0.67      0.67      0.67     29023



In [32]:
text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf' ,GradientBoostingClassifier(max_depth=4, n_estimators=100)),])


text_clf.fit(X_train, y_train)  


predictions = text_clf.predict(X_test)

In [33]:
print(metrics.confusion_matrix(y_test,predictions))

[[5987 2235 1827]
 [2486 6558  825]
 [2418 1209 5478]]


In [34]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

       Mixed       0.55      0.60      0.57     10049
    Negative       0.66      0.66      0.66      9869
    Positive       0.67      0.60      0.64      9105

    accuracy                           0.62     29023
   macro avg       0.63      0.62      0.62     29023
weighted avg       0.62      0.62      0.62     29023

